sudo: required
services:
  - docker

before_install:
  - docker build -t vaky91/docker_react -f Dockerfile.dev .

script:
  -  docker run vaky91/docker_react npm run --help

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-north-1-339712864775"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECURE_KEY"
